providers:
    configurations:
        - provider: '@michaelbui99-discount-alerter/salling-provider'
          enable: false
          config:
              AUTH_TOKEN: AUTH_TOKEN
              STORE_IDS:
                  - 67766b50-4cc6-4658-8fc4-a9b2db468f91
channels:
    configurations:
        - channel: '@michaelbui99-discount-alerter/discord-notification-channel'
          config:
              WEBHOOK: WEBHOOK
storage:
    use: '@michaelbui99-discount-alerter/in-memory-storage'
    configurations:
        - storage: '@michaelbui99-discount-alerter/postgres-storage'
          config:
              db: 'postgres'
              host: 'http://localhost'
              port: '5432'
              user: 'postgres'
              password: 'postgres'
        - storage: '@michaelbui99-discount-alerter/in-memory-storage'
          config:
              foo: 'bar'

server:
    port: 8080

tracker:
    trackSchedule: '*/30 * * * *'
