providers:
    configurations:
        - provider: '@michaelbui99-discount-alerter/salling-provider'
          config:
              AUTH_TOKEN: TOKEN
              STORE_IDS:
                  - ID1
                  - ID2
channels:
    configurations:
        - channel: '@michaelbui99-discount-alerter/discord-channel'
          config:
              webhook: WEB_HOOK
server:
    port: 8080

tracker:
    trackSchedule: '*/30 * * * *'
