FROM node:20.14.0 as build
WORKDIR /app
COPY apps/client /app/apps/client
COPY packages /app/packages
COPY ./package*.json /app/
RUN npm ci
RUN npm run build-client

FROM nginx 
COPY --from=build /app/apps/client/dist/client/browser /usr/share/nginx/html
EXPOSE 80